"""Application-layer vNext normalized immutable revision serving substrate.

Provides ``ParsedKnowledgeRevision``, pure builders, frozen data structures,
and deterministic structural graph indexes over already-decoded vNext knowledge primitives.
"""

from __future__ import annotations

from .builder import (
    DecodedKnowledgeContent,
    build_parsed_knowledge_revision,
    build_parsed_knowledge_revision_from_records,
)
from .errors import (
    LegacyCompatibilityIntegrityError,
    RevisionStructuralIntegrityError,
)
from .frozen_json import (
    FrozenDict,
    FrozenJsonValue,
    canonical_json_bytes,
    canonical_json_text,
    freeze_json_value,
    thaw_json_value,
)
from .legacy_compat import (
    COMPATIBILITY_DOMAIN_CONTRACT_ID,
    COMPATIBILITY_DOMAIN_CONTRACT_REVISION,
    COMPATIBILITY_MANIFEST_SHA256,
    COMPATIBILITY_MAPPING_REVISION,
    LegacyCompatibilityManifest,
    build_historical_semantic_witness,
    build_parsed_revision_semantic_witness,
    compute_legacy_compatibility_key,
    compute_mapping_implementation_digest,
    decode_legacy_graph_revision,
    decode_legacy_stored_graph_revision,
    load_legacy_world_compat_manifest,
    validate_stored_legacy_graph_revision,
    verify_historical_semantic_parity,
    verify_legacy_compatibility_manifest,
)
from .model import (
    PARSED_REVISION_FORMAT_VERSION,
    ParsedKnowledgeRevision,
    compute_compatibility_key,
    compute_semantic_digest,
)
from .records import (
    ParsedAssertion,
    ParsedAssertionMetadata,
    ParsedAssertionValue,
    ParsedDomainContractRef,
    ParsedDomainMetadataEntry,
    ParsedDomainTemporalScope,
    ParsedEntity,
    ParsedEntityRefValue,
    ParsedEvidenceRef,
    ParsedIdentityAlias,
    ParsedKnowledgeRevisionIdentity,
    ParsedLabelsAllVisibility,
    ParsedLabelsAnyVisibility,
    ParsedLiteralValue,
    ParsedMigrationOriginRef,
    ParsedPublicVisibility,
    ParsedScopeBinding,
    ParsedSemanticProfileRef,
    ParsedTemporalScope,
    ParsedTermRefValue,
    ParsedTimelessTemporalScope,
    ParsedUnknownTemporalScope,
    ParsedUtcIntervalTemporalScope,
    ParsedVisibility,
)

__all__ = [
    "COMPATIBILITY_DOMAIN_CONTRACT_ID",
    "COMPATIBILITY_DOMAIN_CONTRACT_REVISION",
    "COMPATIBILITY_MANIFEST_SHA256",
    "COMPATIBILITY_MAPPING_REVISION",
    "PARSED_REVISION_FORMAT_VERSION",
    "DecodedKnowledgeContent",
    "FrozenDict",
    "FrozenJsonValue",
    "LegacyCompatibilityIntegrityError",
    "LegacyCompatibilityManifest",
    "ParsedAssertion",
    "ParsedAssertionMetadata",
    "ParsedAssertionValue",
    "ParsedDomainContractRef",
    "ParsedDomainMetadataEntry",
    "ParsedDomainTemporalScope",
    "ParsedEntity",
    "ParsedEntityRefValue",
    "ParsedEvidenceRef",
    "ParsedIdentityAlias",
    "ParsedKnowledgeRevision",
    "ParsedKnowledgeRevisionIdentity",
    "ParsedLabelsAllVisibility",
    "ParsedLabelsAnyVisibility",
    "ParsedLiteralValue",
    "ParsedMigrationOriginRef",
    "ParsedPublicVisibility",
    "ParsedScopeBinding",
    "ParsedSemanticProfileRef",
    "ParsedTemporalScope",
    "ParsedTermRefValue",
    "ParsedTimelessTemporalScope",
    "ParsedUnknownTemporalScope",
    "ParsedUtcIntervalTemporalScope",
    "ParsedVisibility",
    "RevisionStructuralIntegrityError",
    "build_historical_semantic_witness",
    "build_parsed_knowledge_revision",
    "build_parsed_knowledge_revision_from_records",
    "build_parsed_revision_semantic_witness",
    "canonical_json_bytes",
    "canonical_json_text",
    "compute_compatibility_key",
    "compute_legacy_compatibility_key",
    "compute_mapping_implementation_digest",
    "compute_semantic_digest",
    "decode_legacy_graph_revision",
    "decode_legacy_stored_graph_revision",
    "freeze_json_value",
    "load_legacy_world_compat_manifest",
    "thaw_json_value",
    "validate_stored_legacy_graph_revision",
    "verify_historical_semantic_parity",
    "verify_legacy_compatibility_manifest",
]
