"""Application-layer vNext normalized immutable revision serving substrate.

Provides ``ParsedKnowledgeRevision``, pure builders, frozen data structures,
and deterministic structural graph indexes over already-decoded vNext knowledge primitives.
"""

from __future__ import annotations

from .admission import (
    AdmissionWorkCounts,
    AlwaysAdmitPolicy,
    CandidateAdmissionResult,
    CandidateExclusion,
    ClaimModeFilterPolicy,
    DomainAdmissionPolicyRegistry,
    ExcludeByAssertionIdPolicy,
)
from .builder import (
    DecodedKnowledgeContent,
    build_parsed_knowledge_revision,
    build_parsed_knowledge_revision_from_records,
)
from .entity_reads import (
    CompleteEntityLookupResult,
    EntityLookupResult,
    EntityReadCompleteness,
    EntityReadIdentity,
    EntityReadService,
    EntityReadSourceArtifact,
    EntityReadSourceRevision,
    EntityReadWorkCounts,
)
from .errors import (
    CandidateAdmissionIntegrityError,
    EntityReadIntegrityError,
    EvidenceReadIntegrityError,
    GovernedMaterializationIntegrityError,
    KnowledgePublicationIntegrityError,
    KnowledgeReadContextIntegrityError,
    KnowledgeStaleParentRevisionError,
    LegacyCompatibilityIntegrityError,
    NeighborhoodReadIntegrityError,
    RevisionStructuralIntegrityError,
    SearchReadIntegrityError,
)
from .evidence_reads import (
    AssertionEvidenceResult,
    EvidenceLookupResult,
    EvidenceReadIdentity,
    EvidenceReadService,
    SourceAnchor,
    SourceAnchorResolution,
)
from .frozen_json import (
    FrozenDict,
    FrozenJsonValue,
    canonical_json_bytes,
    canonical_json_text,
    freeze_json_value,
    thaw_json_value,
)
from .legacy_compat import (
    COMPATIBILITY_DOMAIN_CONTRACT_ID,
    COMPATIBILITY_DOMAIN_CONTRACT_REVISION,
    COMPATIBILITY_MANIFEST_SHA256,
    COMPATIBILITY_MAPPING_REVISION,
    LegacyCompatibilityManifest,
    build_historical_semantic_witness,
    build_parsed_revision_semantic_witness,
    compute_legacy_compatibility_key,
    compute_mapping_implementation_digest,
    decode_legacy_graph_revision,
    decode_legacy_stored_graph_revision,
    load_legacy_world_compat_manifest,
    validate_stored_legacy_graph_revision,
    verify_historical_semantic_parity,
    verify_legacy_compatibility_manifest,
)
from .materialization import (
    NATIVE_VNEXT_GRAPH_SCHEMA,
    GovernedMaterializationResult,
    GovernedPublicationIdentity,
    materialize_governed_revision,
)
from .model import (
    PARSED_REVISION_FORMAT_VERSION,
    ParsedKnowledgeRevision,
    compute_compatibility_key,
    compute_semantic_digest,
)
from .neighborhood import (
    MAX_NEIGHBORHOOD_SEED_COUNT,
    NeighborhoodLayerWork,
    NeighborhoodReadIdentity,
    NeighborhoodReadService,
    NeighborhoodResult,
    NeighborhoodWorkCounts,
)
from .provenance import InMemoryKnowledgeSourceReader, KnowledgeProvenanceSnapshot
from .publication import publish_governed_materialization
from .read_context import KnowledgeReadContext
from .records import (
    ParsedAssertion,
    ParsedAssertionMetadata,
    ParsedAssertionValue,
    ParsedDomainContractRef,
    ParsedDomainMetadataEntry,
    ParsedDomainTemporalScope,
    ParsedEntity,
    ParsedEntityRefValue,
    ParsedEvidenceRef,
    ParsedIdentityAlias,
    ParsedKnowledgeRevisionIdentity,
    ParsedLabelsAllVisibility,
    ParsedLabelsAnyVisibility,
    ParsedLiteralValue,
    ParsedMigrationOriginRef,
    ParsedPublicVisibility,
    ParsedScopeBinding,
    ParsedSemanticProfileRef,
    ParsedTemporalScope,
    ParsedTermRefValue,
    ParsedTimelessTemporalScope,
    ParsedUnknownTemporalScope,
    ParsedUtcIntervalTemporalScope,
    ParsedVisibility,
    PublishedKnowledgeRevision,
)
from .revision_ids import compute_knowledge_revision_id
from .search import (
    SearchCompleteness,
    SearchHit,
    SearchReadIdentity,
    SearchReadService,
    SearchResult,
)

__all__ = [
    "COMPATIBILITY_DOMAIN_CONTRACT_ID",
    "COMPATIBILITY_DOMAIN_CONTRACT_REVISION",
    "COMPATIBILITY_MANIFEST_SHA256",
    "COMPATIBILITY_MAPPING_REVISION",
    "MAX_NEIGHBORHOOD_SEED_COUNT",
    "NATIVE_VNEXT_GRAPH_SCHEMA",
    "PARSED_REVISION_FORMAT_VERSION",
    "AdmissionWorkCounts",
    "AlwaysAdmitPolicy",
    "AssertionEvidenceResult",
    "CandidateAdmissionIntegrityError",
    "CandidateAdmissionResult",
    "CandidateExclusion",
    "ClaimModeFilterPolicy",
    "CompleteEntityLookupResult",
    "DecodedKnowledgeContent",
    "DomainAdmissionPolicyRegistry",
    "EntityLookupResult",
    "EntityReadCompleteness",
    "EntityReadIdentity",
    "EntityReadIntegrityError",
    "EntityReadService",
    "EntityReadSourceArtifact",
    "EntityReadSourceRevision",
    "EntityReadWorkCounts",
    "EvidenceLookupResult",
    "EvidenceReadIdentity",
    "EvidenceReadIntegrityError",
    "EvidenceReadService",
    "ExcludeByAssertionIdPolicy",
    "FrozenDict",
    "FrozenJsonValue",
    "GovernedMaterializationIntegrityError",
    "GovernedMaterializationResult",
    "GovernedPublicationIdentity",
    "InMemoryKnowledgeSourceReader",
    "KnowledgeProvenanceSnapshot",
    "KnowledgePublicationIntegrityError",
    "KnowledgeReadContext",
    "KnowledgeReadContextIntegrityError",
    "KnowledgeStaleParentRevisionError",
    "LegacyCompatibilityIntegrityError",
    "LegacyCompatibilityManifest",
    "NeighborhoodLayerWork",
    "NeighborhoodReadIdentity",
    "NeighborhoodReadIntegrityError",
    "NeighborhoodReadService",
    "NeighborhoodResult",
    "NeighborhoodWorkCounts",
    "ParsedAssertion",
    "ParsedAssertionMetadata",
    "ParsedAssertionValue",
    "ParsedDomainContractRef",
    "ParsedDomainMetadataEntry",
    "ParsedDomainTemporalScope",
    "ParsedEntity",
    "ParsedEntityRefValue",
    "ParsedEvidenceRef",
    "ParsedIdentityAlias",
    "ParsedKnowledgeRevision",
    "ParsedKnowledgeRevisionIdentity",
    "ParsedLabelsAllVisibility",
    "ParsedLabelsAnyVisibility",
    "ParsedLiteralValue",
    "ParsedMigrationOriginRef",
    "ParsedPublicVisibility",
    "ParsedScopeBinding",
    "ParsedSemanticProfileRef",
    "ParsedTemporalScope",
    "ParsedTermRefValue",
    "ParsedTimelessTemporalScope",
    "ParsedUnknownTemporalScope",
    "ParsedUtcIntervalTemporalScope",
    "ParsedVisibility",
    "PublishedKnowledgeRevision",
    "RevisionStructuralIntegrityError",
    "SearchCompleteness",
    "SearchHit",
    "SearchReadIdentity",
    "SearchReadIntegrityError",
    "SearchReadService",
    "SearchResult",
    "SourceAnchor",
    "SourceAnchorResolution",
    "build_historical_semantic_witness",
    "build_parsed_knowledge_revision",
    "build_parsed_knowledge_revision_from_records",
    "build_parsed_revision_semantic_witness",
    "canonical_json_bytes",
    "canonical_json_text",
    "compute_compatibility_key",
    "compute_knowledge_revision_id",
    "compute_legacy_compatibility_key",
    "compute_mapping_implementation_digest",
    "compute_semantic_digest",
    "decode_legacy_graph_revision",
    "decode_legacy_stored_graph_revision",
    "freeze_json_value",
    "load_legacy_world_compat_manifest",
    "materialize_governed_revision",
    "publish_governed_materialization",
    "thaw_json_value",
    "validate_stored_legacy_graph_revision",
    "verify_historical_semantic_parity",
    "verify_legacy_compatibility_manifest",
]
