"""MIND-owned minting and atomic provisioning of empty native spaces."""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import uuid4

from dungeonmind.contracts.semantic_profile import SemanticProfileRef
from dungeonmind.contracts.vnext.domain import (
    DomainContractDescriptor,
    DomainContractRef,
    SemanticProfileDescriptorV2,
    SemanticProfileDescriptorV3,
)
from dungeonmind.contracts.vnext.knowledge import PublishKnowledgeRevisionCommand
from dungeonmind.contracts.vnext.space_provisioning import KnowledgeSpaceProvisioningReceipt
from dungeonmind.domain.canonical import canonical_sha256
from dungeonmind.domain.errors import DungeonMindError, PersistenceIntegrityError

from .authority import revision_from_command
from .builder import build_parsed_knowledge_revision
from .errors import KnowledgePublicationIntegrityError
from .materialization import (
    NATIVE_VNEXT_GRAPH_SCHEMA,
    decode_native_graph_payload,
    encode_native_graph_payload,
)
from .ports import KnowledgeRevisionRepository
from .publication import get_publication_receipt

_PUBLICATION_ID = "space-genesis"
_MAX_SPACE_ID_COLLISIONS = 8


class KnowledgeSpaceProvisioningConflictError(DungeonMindError):
    """An allocation key has already been bound to a different request."""

    code = "knowledge_space_provisioning_conflict"

    def __init__(self, *, allocation_id: str) -> None:
        super().__init__(
            "space allocation identity is already bound to a different request",
            details={"allocation_id": allocation_id},
        )
        self.allocation_id = allocation_id


class _KnowledgeSpaceIdCollisionError(Exception):
    """Internal signal to mint another candidate after an occupied-ID race."""


def _provisioning_request_sha256(command: PublishKnowledgeRevisionCommand) -> str:
    """Bind the durable idempotency key to semantic genesis intent only."""
    request = command.model_dump(mode="json")
    request.pop("space_id")
    request.pop("created_at")
    return canonical_sha256(request)


def _new_space_id() -> str:
    return f"space:dm:{uuid4().hex}"


def create_empty_space(
    *,
    repository: KnowledgeRevisionRepository,
    allocation_id: str,
    created_at: datetime,
    domain_contract: DomainContractDescriptor,
    semantic_profile: SemanticProfileDescriptorV2 | SemanticProfileDescriptorV3,
) -> KnowledgeSpaceProvisioningReceipt:
    """Mint and atomically initialize one empty KnowledgeSpace.

    ``allocation_id`` is only an idempotency key; callers cannot choose the
    resulting ``space_id``. Time is generated by the caller but is not part of
    semantic request identity, so a retry may use a fresh timestamp.
    """
    if not isinstance(allocation_id, str) or not allocation_id.strip():
        raise KnowledgePublicationIntegrityError("allocation_id_blank")
    if not isinstance(created_at, datetime) or created_at.utcoffset() is None:
        raise KnowledgePublicationIntegrityError("created_at_not_timezone_aware")
    if not isinstance(domain_contract, DomainContractDescriptor):
        raise KnowledgePublicationIntegrityError("domain_contract_type_invalid")
    if not isinstance(
        semantic_profile, (SemanticProfileDescriptorV2, SemanticProfileDescriptorV3)
    ):
        raise KnowledgePublicationIntegrityError("semantic_profile_type_invalid")

    domain_snapshot = DomainContractDescriptor.model_validate(
        domain_contract.model_dump(mode="json")
    )
    profile_type = type(semantic_profile)
    profile_snapshot = profile_type.model_validate(semantic_profile.model_dump(mode="json"))
    payload = encode_native_graph_payload(
        entities={}, assertions={}, aliases={}, evidence={}
    )
    decoded = decode_native_graph_payload(payload)

    for _ in range(_MAX_SPACE_ID_COLLISIONS):
        space_id = _new_space_id()
        command = PublishKnowledgeRevisionCommand(
            space_id=space_id,
            parent_revision_id=None,
            expected_parent_revision_id=None,
            operation_ids=[_PUBLICATION_ID],
            graph_schema=NATIVE_VNEXT_GRAPH_SCHEMA,
            graph_payload=payload,
            domain_contract_ref=DomainContractRef(
                domain_id=domain_snapshot.domain_id,
                domain_revision=domain_snapshot.domain_revision,
                descriptor_sha256=canonical_sha256(
                    domain_snapshot.model_dump(mode="json")
                ),
            ),
            semantic_profile_ref=SemanticProfileRef(
                profile_id=profile_snapshot.profile_id,
                profile_revision=profile_snapshot.profile_revision,
                descriptor_sha256=canonical_sha256(
                    profile_snapshot.model_dump(mode="json")
                ),
            ),
            migration_origin_ref=None,
            created_at=created_at.astimezone(UTC),
        )
        expected = revision_from_command(command)
        build_parsed_knowledge_revision(revision=expected, decoded_content=decoded)
        request_sha = _provisioning_request_sha256(command)
        try:
            receipt = repository.provision_empty_space(
                command,
                allocation_id=allocation_id,
                request_sha256=request_sha,
                publication_id=_PUBLICATION_ID,
            )
            if (
                receipt.allocation_id != allocation_id
                or receipt.request_sha256 != request_sha
                or receipt.publication_receipt.publication_id != _PUBLICATION_ID
            ):
                raise PersistenceIntegrityError(
                    "space provisioning receipt request identity drift"
                )
            publication = get_publication_receipt(
                receipt.space_id, _PUBLICATION_ID, repository=repository
            )
            if publication is None or publication != receipt.publication_receipt:
                raise PersistenceIntegrityError(
                    "space provisioning receipt publication mismatch"
                )
            stored = repository.get_revision(
                receipt.space_id, publication.published_revision_id
            )
            if stored is None or stored.graph_payload != {
                "entities": [],
                "assertions": [],
                "aliases": [],
                "evidence": [],
            }:
                raise PersistenceIntegrityError(
                    "space provisioning receipt does not identify empty genesis"
                )
            if stored.revision.parent_revision_id is not None:
                raise PersistenceIntegrityError(
                    "space provisioning genesis unexpectedly has a parent"
                )
            return receipt
        except _KnowledgeSpaceIdCollisionError:
            continue
    raise KnowledgePublicationIntegrityError("space_id_collision_retry_exhausted")
