"""DungeonMind public contracts — the versioned wire API.

Every durable or wire contract is a strict Pydantic v2 model with a
``schema_version`` literal. Contracts change only by versioned supersession.
"""

from .capability import (
    CAPABILITY_POLICY_SCHEMA,
    CapabilityCategory,
    CapabilityEffect,
    CapabilityPolicy,
    GraphScope,
    ToolCapabilityRule,
)
from .contribution import (
    GRAPH_CONTRIBUTION_SCHEMA,
    AcceptanceState,
    ContributionSourceKind,
    ContributionStatus,
    GraphContribution,
    GraphContributionAssertion,
)
from .evidence import (
    EVIDENCE_REF_SCHEMA,
    SOURCE_ARTIFACT_SCHEMA,
    SOURCE_REVISION_SCHEMA,
    EvidenceRef,
    EvidenceRole,
    SourceArtifact,
    SourceDomain,
    SourceRevision,
    SourceStatus,
)
from .graph import (
    GRAPH_HEAD_SCHEMA,
    GRAPH_REVISION_SCHEMA,
    PublishRevisionCommand,
    StoredGraphRevision,
    WorldGraphHead,
    WorldGraphRevision,
)
from .identity import (
    IDENTITY_DECISION_SCHEMA,
    IdentityDecisionKind,
    IdentityDecisionRecord,
    IdentityDecisionStatus,
    IdentityOutcome,
)
from .ids import new_id
from .mind_turn import (
    MIND_TURN_SCHEMA,
    CallerScope,
    ContextChange,
    MindTurnRequest,
    MindTurnResponse,
    SemanticProjection,
    SuggestedAction,
    SurfaceContext,
)
from .projection import (
    PROJECTION_REQUEST_SCHEMA,
    PROJECTION_SNAPSHOT_SCHEMA,
    Admissibility,
    FocusKind,
    ProjectionFocus,
    ProjectionSnapshot,
    ScopeMode,
    WorldGraphProjectionRequest,
)
from .retrieval import (
    RETRIEVAL_SESSION_SCHEMA,
    Claim,
    ClaimAuthority,
    ClaimStatus,
    Coverage,
    DiagnosticEntry,
    GraphRetrievalSession,
    OperationOutcome,
    ResolvedReferent,
    RetrievalOperation,
    RetrievalOperationKind,
    SourceAnchor,
    SourceRead,
)
from .semantic import (
    EMBEDDING_RUN_SCHEMA,
    SEMANTIC_DOCUMENT_SCHEMA,
    CandidateChannel,
    EmbeddingRun,
    EmbeddingRunStatus,
    SemanticCandidate,
    SemanticDocument,
    SemanticDocumentKind,
    SemanticQuery,
)
from .vocabulary import CanonState, EpistemicKind, Visibility

__all__ = [
    "CAPABILITY_POLICY_SCHEMA",
    "EMBEDDING_RUN_SCHEMA",
    "EVIDENCE_REF_SCHEMA",
    "GRAPH_CONTRIBUTION_SCHEMA",
    "GRAPH_HEAD_SCHEMA",
    "GRAPH_REVISION_SCHEMA",
    "IDENTITY_DECISION_SCHEMA",
    "MIND_TURN_SCHEMA",
    "PROJECTION_REQUEST_SCHEMA",
    "PROJECTION_SNAPSHOT_SCHEMA",
    "RETRIEVAL_SESSION_SCHEMA",
    "SEMANTIC_DOCUMENT_SCHEMA",
    "SOURCE_ARTIFACT_SCHEMA",
    "SOURCE_REVISION_SCHEMA",
    "AcceptanceState",
    "Admissibility",
    "CallerScope",
    "CandidateChannel",
    "CanonState",
    "CapabilityCategory",
    "CapabilityEffect",
    "CapabilityPolicy",
    "Claim",
    "ClaimAuthority",
    "ClaimStatus",
    "ContextChange",
    "ContributionSourceKind",
    "ContributionStatus",
    "Coverage",
    "DiagnosticEntry",
    "EmbeddingRun",
    "EmbeddingRunStatus",
    "EpistemicKind",
    "EvidenceRef",
    "EvidenceRole",
    "FocusKind",
    "GraphContribution",
    "GraphContributionAssertion",
    "GraphRetrievalSession",
    "GraphScope",
    "IdentityDecisionKind",
    "IdentityDecisionRecord",
    "IdentityDecisionStatus",
    "IdentityOutcome",
    "MindTurnRequest",
    "MindTurnResponse",
    "OperationOutcome",
    "ProjectionFocus",
    "ProjectionSnapshot",
    "PublishRevisionCommand",
    "ResolvedReferent",
    "RetrievalOperation",
    "RetrievalOperationKind",
    "ScopeMode",
    "SemanticCandidate",
    "SemanticDocument",
    "SemanticDocumentKind",
    "SemanticProjection",
    "SemanticQuery",
    "SourceAnchor",
    "SourceArtifact",
    "SourceDomain",
    "SourceRead",
    "SourceRevision",
    "SourceStatus",
    "StoredGraphRevision",
    "SuggestedAction",
    "SurfaceContext",
    "ToolCapabilityRule",
    "Visibility",
    "WorldGraphHead",
    "WorldGraphProjectionRequest",
    "WorldGraphRevision",
    "new_id",
]
