"""The strict, domain-agnostic DungeonMind vNext wire contract namespace.

Only the symbols listed in ``__all__`` are the intentional public surface.
``PUBLIC_CONTRACT_MODELS`` is the exact inventory serialized into the checked-in
schema bundle and must remain a subset of ``__all__``.
"""

from __future__ import annotations

from .common import (
    DomainMetadataEntry,
    DomainTemporalScope,
    EpistemicBasis,
    KnowledgeStanding,
    LabelsAllVisibility,
    LabelsAnyVisibility,
    NonBlankId,
    PublicVisibility,
    QualifiedTerm,
    ScopeBinding,
    ScopeSelector,
    Sha256Hex,
    TemporalScope,
    TimelessTemporalScope,
    UnknownTemporalScope,
    UtcIntervalTemporalScope,
    VisibilityRequirement,
    canonical_json,
    sha256,
)
from .contribution import (
    ContributionDisposition,
    ContributionItem,
    KnowledgeContribution,
    ProposeAssertion,
    ProposeEntity,
    ProposeIdentityDecision,
    RetractAssertion,
    SupersedeAssertion,
)
from .domain import (
    Assertion,
    AssertionMetadata,
    DomainContractDescriptor,
    DomainContractRef,
    Entity,
    EntityRefValue,
    LiteralValue,
    OpenPredicateNamespace,
    SemanticProfileDescriptorV2,
    SemanticProfileDescriptorV3,
    SemanticProfilePredicate,
    TermRefValue,
)
from .knowledge import (
    IdentityAlias,
    IdentityDecisionKind,
    IdentityDecisionStatus,
    IdentityDecisionV3,
    KnowledgeHead,
    KnowledgeRevision,
    MigrationOriginRef,
    PublishKnowledgeRevisionCommand,
)
from .native_source import (
    MAX_NATIVE_TEXT_BYTES,
    MAX_NATIVE_TEXT_SPANS,
    NATIVE_TEXT_BODY_STORAGE,
    NativeSourceAdmissionReceiptV1,
    NativeTextEvidenceSpanRequestV1,
    NativeTextSourceAccessV1,
    NativeTextSourceAdmissionBindingV1,
    NativeTextSourceAdmissionV1,
    NativeTextSourceOriginV1,
    NativeUtf8SpanProofV1,
)
from .projection import FocusRef, ProjectionRequest, ProjectionSnapshot
from .prospective import (
    DurableEntityRef,
    EntityOperand,
    KnowledgeProspectivePublication,
    KnowledgeProspectivePublicationResult,
    ProspectiveAssertionValue,
    ProspectiveContributionItem,
    ProspectiveCreateAssertion,
    ProspectiveCreateEntity,
    ProspectiveEntityRef,
    ProspectiveEntityRefValue,
    ProspectiveKnowledgeContribution,
    ProspectiveResultBinding,
)
from .publication import KnowledgePublicationReceipt
from .source import EvidenceRefV3, SourceArtifactV3, SourceRevisionV2

PUBLIC_CONTRACT_MODELS: tuple[type, ...] = (
    Assertion,
    ContributionDisposition,
    DomainContractDescriptor,
    DomainContractRef,
    Entity,
    EvidenceRefV3,
    IdentityAlias,
    IdentityDecisionV3,
    KnowledgeContribution,
    KnowledgeHead,
    KnowledgeRevision,
    ProjectionRequest,
    ProjectionSnapshot,
    PublishKnowledgeRevisionCommand,
    SemanticProfileDescriptorV2,
    SourceArtifactV3,
    SourceRevisionV2,
)

__all__ = [
    "MAX_NATIVE_TEXT_BYTES",
    "MAX_NATIVE_TEXT_SPANS",
    "NATIVE_TEXT_BODY_STORAGE",
    "PUBLIC_CONTRACT_MODELS",
    "Assertion",
    "AssertionMetadata",
    "ContributionDisposition",
    "ContributionItem",
    "DomainContractDescriptor",
    "DomainContractRef",
    "DomainMetadataEntry",
    "DomainTemporalScope",
    "DurableEntityRef",
    "Entity",
    "EntityOperand",
    "EntityRefValue",
    "EpistemicBasis",
    "EvidenceRefV3",
    "FocusRef",
    "IdentityAlias",
    "IdentityDecisionKind",
    "IdentityDecisionStatus",
    "IdentityDecisionV3",
    "KnowledgeContribution",
    "KnowledgeHead",
    "KnowledgeProspectivePublication",
    "KnowledgeProspectivePublicationResult",
    "KnowledgePublicationReceipt",
    "KnowledgeRevision",
    "KnowledgeStanding",
    "LabelsAllVisibility",
    "LabelsAnyVisibility",
    "LiteralValue",
    "MigrationOriginRef",
    "NativeSourceAdmissionReceiptV1",
    "NativeTextEvidenceSpanRequestV1",
    "NativeTextSourceAccessV1",
    "NativeTextSourceAdmissionBindingV1",
    "NativeTextSourceAdmissionV1",
    "NativeTextSourceOriginV1",
    "NativeUtf8SpanProofV1",
    "NonBlankId",
    "OpenPredicateNamespace",
    "ProjectionRequest",
    "ProjectionSnapshot",
    "ProposeAssertion",
    "ProposeEntity",
    "ProposeIdentityDecision",
    "ProspectiveAssertionValue",
    "ProspectiveContributionItem",
    "ProspectiveCreateAssertion",
    "ProspectiveCreateEntity",
    "ProspectiveEntityRef",
    "ProspectiveEntityRefValue",
    "ProspectiveKnowledgeContribution",
    "ProspectiveResultBinding",
    "PublicVisibility",
    "PublishKnowledgeRevisionCommand",
    "QualifiedTerm",
    "RetractAssertion",
    "ScopeBinding",
    "ScopeSelector",
    "SemanticProfileDescriptorV2",
    "SemanticProfileDescriptorV3",
    "SemanticProfilePredicate",
    "Sha256Hex",
    "SourceArtifactV3",
    "SourceRevisionV2",
    "SupersedeAssertion",
    "TemporalScope",
    "TermRefValue",
    "TimelessTemporalScope",
    "UnknownTemporalScope",
    "UtcIntervalTemporalScope",
    "VisibilityRequirement",
    "canonical_json",
    "sha256",
]
